apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: drones-ingress2
spec:
  rules:
  - http:
      paths:
      - path: /task(/|$)(.*)
        backend:
          serviceName: drones-app-helm-deployment
          servicePort: 4000
      - path: /
        backend:
          serviceName: greyfoods-api-lamp
          servicePort: 80
  tls: 
    - 
      hosts: 
        - aa75e59c5b52245f78bca84a87c33713-1730258908.us-east-1.elb.amazonaws.com

          
     