version: '3'

services:
   
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
        MONGO_INITDB_DATABASE: admin
        MONGO_INITDB_ROOT_USERNAME: droneuser
        MONGO_INITDB_ROOT_PASSWORD: xc892zx22

